const CLUBELO_IDS = {
  'Barcelona':83,'Real Madrid':86,'Atletico':1068,'Villarreal':102,'Betis':244,
  'Sociedad':89,'Bilbao':93,'Sevilla':243,'Valencia':94,'Celta':85,
  'Getafe':2922,'Girona':9812,'Espanyol':88,'Levante':1538,'Mallorca':84,
  'Osasuna':97,'Alaves':96,'Rayo Vallecano':101,'Elche':3751,'Oviedo':92,
  'Arsenal':359,'Man City':382,'Liverpool':364,'Chelsea':363,'Man United':360,
  'Tottenham':367,'Newcastle':361,'Aston Villa':362,'West Ham':371,'Brighton':331,
  'Brentford':337,'Fulham':370,'Crystal Palace':384,'Everton':368,'Burnley':379,
  'Forest':393,'Leeds':357,'Wolves':380,'Bournemouth':349,'Sunderland':366,
  'Bayern':132,'Dortmund':124,'Leverkusen':131,'Frankfurt':125,'RB Leipzig':11420,
  'Stuttgart':134,'Wolfsburg':138,'Freiburg':126,'Augsburg':3841,'Hoffenheim':7911,
  'Gladbach':268,'Hamburg':127,'Mainz':2950,'Koeln':122,'Heidenheim':6418,
  'St Pauli':270,'Union Berlin':598,'Werder':137,
  'Juventus':111,'Inter':110,'Milan':103,'Napoli':114,'Roma':104,
  'Atalanta':105,'Lazio':112,'Fiorentina':109,'Bologna':107,'Torino':239,
  'Genoa':3263,'Udinese':118,'Cagliari':2925,'Lecce':113,'Verona':119,
  'Parma':115,'Como':2572,'Sassuolo':3997,'Cremonese':4050,'Pisa':3956,
  'Paris SG':160,'Marseille':176,'Lyon':167,'Monaco':174,'Lille':166,
  'Rennes':169,'Lens':175,'Nice':2502,'Strasbourg':180,'Nantes':165,
  'Auxerre':172,'Toulouse':179,'Brest':6997,'Angers':7868,'Lorient':273,
  'Metz':177,'Le Havre':3236,'Paris FC':6851,
  'PSV':148,'Feyenoord':142,'Ajax':139,
  'Brugge':570,'St Gillis':5807,'Anderlecht':441,
  'Celtic':256,'Rangers':257,
  'Galatasaray':432,'Fenerbahce':436,'Besiktas':1895,
  'RB Salzburg':2790,
  'Sporting':2250,'Benfica':1929,'Porto':437,'Braga':2994,
  'Famalicao':12698,'Guimaraes':5309,'Gil Vicente':3699,'Arouca':15784,
  'Estoril':12215,'Santa Clara':12215,'Moreirense':3696,'Rio Ave':3822,
  'Nacional':3472,'Alverca':21613,'Casa Pia':21581,'AVS Futebol':22064,
};

const LEAGUE_LABELS = {
  'esp.1': 'La Liga',
  'eng.1': 'Premier League',
  'ger.1': 'Bundesliga',
  'ita.1': 'Serie A',
  'fra.1': 'Ligue 1',
  'por.1': 'Primeira Liga',
  'ned.1': 'Eredivisie',
  'bel.1': 'Pro League',
};

const LEAGUE_COUNTRY = {
  'esp.1': 'ESP', 'eng.1': 'ENG', 'ger.1': 'GER', 'ita.1': 'ITA', 'fra.1': 'FRA', 'por.1': 'POR',
  'ned.1': 'NED', 'bel.1': 'BEL',
};

const LEAGUE_INFO = {
  ENG: { name: 'Premier League',  flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  ESP: { name: 'La Liga',         flag: '🇪🇸' },
  GER: { name: 'Bundesliga',      flag: '🇩🇪' },
  ITA: { name: 'Serie A',         flag: '🇮🇹' },
  FRA: { name: 'Ligue 1',         flag: '🇫🇷' },
  POR: { name: 'Primeira Liga',   flag: '🇵🇹' },
  BEL: { name: 'Pro League',      flag: '🇧🇪' },
  DEN: { name: 'Superliga',       flag: '🇩🇰' },
  NED: { name: 'Eredivisie',      flag: '🇳🇱' },
  RUS: { name: 'Premier League',  flag: '🇷🇺' },
  NOR: { name: 'Eliteserien',     flag: '🇳🇴' },
  TUR: { name: 'Süper Lig',       flag: '🇹🇷' },
  POL: { name: 'Ekstraklasa',     flag: '🇵🇱' },
  GRE: { name: 'Super League',    flag: '🇬🇷' },
  CZE: { name: 'First League',    flag: '🇨🇿' },
  SUI: { name: 'Super League',    flag: '🇨🇭' },
  SWE: { name: 'Allsvenskan',     flag: '🇸🇪' },
  AUT: { name: 'Bundesliga',      flag: '🇦🇹' },
  SCO: { name: 'Premiership',     flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  CRO: { name: 'HNL',             flag: '🇭🇷' },
  ROM: { name: 'SuperLiga',       flag: '🇷🇴' },
  UKR: { name: 'Premier League',  flag: '🇺🇦' },
  HUN: { name: 'NB I',            flag: '🇭🇺' },
  ISR: { name: 'Premier League',  flag: '🇮🇱' },
  SVN: { name: '1. SNL',          flag: '🇸🇮' },
  SRB: { name: 'SuperLiga',       flag: '🇷🇸' },
  BUL: { name: 'First League',    flag: '🇧🇬' },
  CYP: { name: 'First Division',  flag: '🇨🇾' },
  AZE: { name: 'Premier League',  flag: '🇦🇿' },
  SLK: { name: 'Super Liga',      flag: '🇸🇰' },
  KAZ: { name: 'Premier League',  flag: '🇰🇿' },
  IRL: { name: 'League of Ireland', flag: '🇮🇪' },
  ARM: { name: 'Premier League',  flag: '🇦🇲' },
  FIN: { name: 'Veikkausliiga',   flag: '🇫🇮' },
  ISL: { name: 'Úrvalsdeild',     flag: '🇮🇸' },
  BHZ: { name: 'Premier League',  flag: '🇧🇦' },
  LAT: { name: 'Virslīga',        flag: '🇱🇻' },
  MOL: { name: 'National Division', flag: '🇲🇩' },
  ALB: { name: 'Superliga',       flag: '🇦🇱' },
  BLR: { name: 'Vysheyshaya Liga', flag: '🇧🇾' },
  GEO: { name: 'Erovnuli Liga',   flag: '🇬🇪' },
  KOS: { name: 'Football League', flag: '🇽🇰' },
  LIT: { name: 'A Lyga',          flag: '🇱🇹' },
  MAC: { name: 'First Football League', flag: '🇲🇰' },
  EST: { name: 'Meistriliiga',    flag: '🇪🇪' },
  FAR: { name: 'Faroese Premier League', flag: '🇫🇴' },
  MLT: { name: 'Premier League',  flag: '🇲🇹' },
  MNT: { name: 'First League',    flag: '🇲🇪' },
  NIR: { name: 'Premiership',     flag: '🇬🇧' },
  LUX: { name: 'National Division', flag: '🇱🇺' },
};

const TEAMS = [
  { id: 83,    league: 'esp.1', name: 'FC Barcelona',           short: 'Barça'      },
  { id: 86,    league: 'esp.1', name: 'Real Madrid',            short: 'Madrid'     },
  { id: 1068,  league: 'esp.1', name: 'Atlético Madrid',        short: 'Atlético'   },
  { id: 243,   league: 'esp.1', name: 'Sevilla',                short: 'Sevilla'    },
  { id: 94,    league: 'esp.1', name: 'Valencia',               short: 'Valencia'   },
  { id: 102,   league: 'esp.1', name: 'Villarreal',             short: 'Villarreal' },
  { id: 244,   league: 'esp.1', name: 'Real Betis',             short: 'Betis'      },
  { id: 93,    league: 'esp.1', name: 'Athletic Club',          short: 'Athletic'   },
  { id: 89,    league: 'esp.1', name: 'Real Sociedad',          short: 'Sociedad'   },
  { id: 9812,  league: 'esp.1', name: 'Girona',                 short: 'Girona'     },
  { id: 359,   league: 'eng.1', name: 'Arsenal',                short: 'Arsenal'    },
  { id: 363,   league: 'eng.1', name: 'Chelsea',                short: 'Chelsea'    },
  { id: 364,   league: 'eng.1', name: 'Liverpool',              short: 'Liverpool'  },
  { id: 382,   league: 'eng.1', name: 'Manchester City',        short: 'Man City'   },
  { id: 360,   league: 'eng.1', name: 'Manchester United',      short: 'Man Utd'    },
  { id: 367,   league: 'eng.1', name: 'Tottenham Hotspur',      short: 'Spurs'      },
  { id: 361,   league: 'eng.1', name: 'Newcastle United',       short: 'Newcastle'  },
  { id: 362,   league: 'eng.1', name: 'Aston Villa',            short: 'Villa'      },
  { id: 371,   league: 'eng.1', name: 'West Ham United',        short: 'West Ham'   },
  { id: 331,   league: 'eng.1', name: 'Brighton & Hove Albion', short: 'Brighton'   },
  { id: 132,   league: 'ger.1', name: 'Bayern Munich',          short: 'Bayern'     },
  { id: 124,   league: 'ger.1', name: 'Borussia Dortmund',      short: 'Dortmund'   },
  { id: 131,   league: 'ger.1', name: 'Bayer Leverkusen',       short: 'Leverkusen' },
  { id: 125,   league: 'ger.1', name: 'Eintracht Frankfurt',    short: 'Frankfurt'  },
  { id: 11420, league: 'ger.1', name: 'RB Leipzig',             short: 'Leipzig'    },
  { id: 134,   league: 'ger.1', name: 'VfB Stuttgart',          short: 'Stuttgart'  },
  { id: 111,   league: 'ita.1', name: 'Juventus',               short: 'Juventus'   },
  { id: 110,   league: 'ita.1', name: 'Internazionale',         short: 'Inter'      },
  { id: 103,   league: 'ita.1', name: 'AC Milan',               short: 'Milan'      },
  { id: 114,   league: 'ita.1', name: 'Napoli',                 short: 'Napoli'     },
  { id: 104,   league: 'ita.1', name: 'AS Roma',                short: 'Roma'       },
  { id: 105,   league: 'ita.1', name: 'Atalanta',               short: 'Atalanta'   },
  { id: 112,   league: 'ita.1', name: 'Lazio',                  short: 'Lazio'      },
  { id: 109,   league: 'ita.1', name: 'Fiorentina',             short: 'Fiorentina' },
  { id: 160,   league: 'fra.1', name: 'Paris Saint-Germain',    short: 'PSG'        },
  { id: 176,   league: 'fra.1', name: 'Marseille',              short: 'Marseille'  },
  { id: 167,   league: 'fra.1', name: 'Lyon',                   short: 'Lyon'       },
  { id: 174,   league: 'fra.1', name: 'AS Monaco',              short: 'Monaco'     },
  { id: 166,   league: 'fra.1', name: 'Lille',                  short: 'Lille'      },
  { id: 1929,  league: 'por.1', name: 'Benfica',                short: 'Benfica'    },
  { id: 437,   league: 'por.1', name: 'FC Porto',               short: 'Porto'      },
  { id: 2250,  league: 'por.1', name: 'Sporting CP',            short: 'Sporting'   },
  { id: 2994,  league: 'por.1', name: 'Braga',                  short: 'Braga'      },
  { id: 5309,  league: 'por.1', name: 'Vitória de Guimarães',   short: 'Vitória'    },
  { id: 3822,  league: 'por.1', name: 'Rio Ave',                short: 'Rio Ave'    },

  { id: 148,   league: 'ned.1', name: 'PSV Eindhoven',           short: 'PSV'        },
  { id: 139,   league: 'ned.1', name: 'Ajax',                    short: 'Ajax'       },
  { id: 142,   league: 'ned.1', name: 'Feyenoord',               short: 'Feyenoord'  },
  { id: 152,   league: 'ned.1', name: 'FC Twente',               short: 'Twente'     },
  { id: 140,   league: 'ned.1', name: 'AZ Alkmaar',              short: 'AZ'         },
  { id: 153,   league: 'ned.1', name: 'FC Utrecht',              short: 'Utrecht'    },

  { id: 570,   league: 'bel.1', name: 'Club Brugge',             short: 'Brugge'     },
  { id: 5807,  league: 'bel.1', name: 'Union St-Gilloise',       short: 'Union SG'   },
  { id: 441,   league: 'bel.1', name: 'Anderlecht',              short: 'Anderlecht' },
  { id: 3611,  league: 'bel.1', name: 'KAA Gent',               short: 'Gent'       },
];
